### ISSUE TITLE
How to use libraries?

### ISSUE THREAD

**Issue by esprehn** [GoogleChromeLabs/clooney#12]
Sending the class across is really cool, but I'm trying to figure out how it would reference libraries for using in that class. For example I need to do `import * as moment from 'moment'` over there somehow?

**Comment by surma** [comment]
Ohai @esprehn 👋 

yes, the API currently is a bit deceptive. Any extended class or something probably won’t work. Eventually (when modules land in workers), I‘d like to change the API to `Clooney.spawn(modulePath, exportName)`. 

But for now, I thought I’d let people play with this. 

If accessing globals becomes a problem, this can be solved via a custom strategy. But I haven’t done that yet.
