### ISSUE TITLE
Enabling spawning actors for a function

### ISSUE THREAD

**Issue by woutervanvliet** [GoogleChromeLabs/clooney#16]
Would be great of we could spawn an Actor for a function, rather than only classes. I'd like to do something like this:

```
const doHeavyWork = Clooney.spawn((forMillis) => {
  let arr = [];
  const start = Date.now();
  while(Date.now() - start < forMillis) {
    arr = [...arr, Date.now()];
  }

  // return a promise that waits for the some time again, just to illustrate
  // how I imagine Clooney to handle promises
  return new Promise((resolve) => setTimeout(resolve, forMillis, arr.length);
});

const iterations = await doHeavyWork(1000);
```

As I imagine it working, the promise returned from `Clooney.spawn` in this case would wait for both whatever it takes to spawn as well as for the promise returned from `doHeavyWork`. Maybe spawning would even be delayed until the function is actually called?

**Comment by surma** [comment]
I was thinking about this myself, but it would take a good amount of additional code for something that doesn’t yield much benefit except for some syntactic sugar. I don’t think it’s worth it.

For example, your code example works right now with only some minimal changes:

```js
const x = Clooney.spawn(class X {doHeavyWork(forMillis) {
  let arr = [];
  const start = Date.now();
  while(Date.now() - start < forMillis) {
    arr = [...arr, Date.now()];
  }

  // return a promise that waits for the some time again, just to illustrate
  // how I imagine Clooney to handle promises
  return new Promise((resolve) => setTimeout(resolve, forMillis, arr.length);
});

const iterations = await x.doHeavyWork(1000);
```

Also, thanks for reminding me that I need to put something about promises in the README, cause Clooney totally handles promises already. Example:

```js
class Actor {
  timeoutThing() {
    return new Promise(resolve => setTimeout(_ => resolve('ohai'), 1000));
  }
}

const instance = await strategy.spawn(Actor);
alert(await instance.timeoutThing());
```

Does that make sense? Or am I missing your point?

**Comment by woutervanvliet** [comment]
Ah, of course! I keep forgetting that `class X {}` just returns a value which an be send into any function, without "living anywhere else". I guess
```
const runner = await Clooney.spawn(class {run() { /* do work */ }});
runner.run();
```
would be the shortest way to write that. Could be made even shorter if spawn would return a proxy instead of a promise. That way, one would be able to start calling functions on the spawning actors without waiting. But that too is mostly sugar that can be added with a little wrapper.

**Comment by surma** [comment]
Fun fact: `spawn` is technically synchronous (it’s a thin wrapper around `Comlink.proxy()`), but I have a couple of ideas where some asynchronous setup work is needed like fetching resources. I don’t see how waiting (or then’ing) could be an issue.

**Comment by woutervanvliet** [comment]
Don't you mean `await`ing ;-)

Either way, not so much of a problem. I just generally like to chain promises as much as possible to not have to await too much in application code.

**Comment by surma** [comment]
Lol, yes `await`’ing! (edited)

But are you aware that `await`ing and `then`ing are the same thing? If you like chaining promises, then that’s already possible:

```js
Clooney.spawn(myActor)
  .then(instance => instance.runExpensiveCode())
  .then(result => alert(result)); // lol
```

**Comment by woutervanvliet** [comment]
This is getting quite far away from the original topic ;-).

Yes, I know that `then`ing and `await`ing are effectively the same thing. But if a library makes me `await` the same pattern over and over again, `then` I would typically write a wrapper to keep my application code more concise, making this possible:

```
George.spawn(myActor).runExpensiveCode()
  .then(result => alert(result));
```
