### ISSUE TITLE
Browser support info

### ISSUE THREAD

**Issue by krystian50** [GoogleChromeLabs/clooney#197]
It would be nice to have info in docs about browser support. 

BTW Does it support IE11?
Judging by [Workers](https://developer.mozilla.org/en-US/docs/Web/API/Worker) support it does, but it can be limited.

**Comment by surma** [comment]
Clooney has the same support matrix as [Comlink](https://github.com/GoogleChromeLabs/comlink), so IE11 is not supported out of the box, as it relies on ES6 proxies.
