### ISSUE TITLE
I don't understand :-(

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChromeLabs/clooney#2]
I'm having a bit of trouble understanding how Clooney manages multiple actors. I get the feeling that Clooney should make it possible to perform, say, a MapReduce using using multiple isolated workers, but I'm not sure how to do this.

Async, but not parallel:

```js
const fn = (n) => Promise.resolve(n + 1);
Promise.all([10, 20, 30].map(fn)).then(console.log);
// -> [11, 21, 31] (in some order)
```

Is there some way to make multiple `fn()` calls execute in parallel using Clooney?

**Comment by surma** [comment]
MapReduce is an interesting idea. Maybe I should put this in the README?

But yes, you can create multiple workers!

```js
class MyMapJob {
  doTheThing(data) {
    // ... do all the hard work ...
    return result;
  }
}

// Spawn the same actor multiple times
const instances = [
  await Clooney.spawn(MyMapJob), 
  await Clooney.spawn(MyMapJob), 
  /*...*/ 
  await Clooney.spawn(MyMapJob)
];

const results = await Promise.all(
  instance.map(async instance => await instance.doTheThing(data))
);
const result = results.reduce(/* ... */);
```

Keep in mind that workers share a worker by default. If you want to have multiple threads, you need to create your own instance of a strategy:

```js
const strategy = new Clooney.RoundRobinStrategy({
  maxNumContainers: navigator.hardwareConcurrency
});

class MyMapJob {
  doTheThing(data) {
    // ... do all the hard work ...
    return result;
  }
}

// Spawn the same actor multiple times
const instances = [
  await strategy.spawn(MyMapJob), 
  await strategy.spawn(MyMapJob), 
  /*...*/ 
  await strategy.spawn(MyMapJob)
];

const results = await Promise.all(
  instance.map(async instance => await instance.doTheThing(data))
);
const result = results.reduce(/* ... */);
```

Please re-open if this didn’t answer your question :)

**Comment by ithinkihaveacat** [comment]
Thanks for the explanation!

I need to think all this through a bit more … I feel a bit uneasy about the proxying, etc. that is done (or can be) to try to eliminate differences between worker code and non-worker code, not sure if that abstraction is worth it.

**Comment by surma** [comment]
Where do you see the downsides? 

This is most definitely supposed to be an off-the-shelf solution that probably won’t scale to large apps.
