### ISSUE TITLE
Cloony vs Comlink

### ISSUE THREAD

**Issue by davidnagli** [GoogleChromeLabs/clooney#21]
How does **GoogleChromeLabs/Cloony** compare to [**GoogleChromeLabs/comlink**](https://github.com/GoogleChromeLabs/comlink)? In what situations should Comlink be used over Cloony?

By the looks of it, Cloony is a more high level and easy-to-use option, while comlink provides more low level control and configurability...

**Comment by surma** [comment]
You are pretty much spot on. Here’s an excerpt from Comlink’s README:

> Note: Comlink’s goal is to be a building-block for higher-level abstraction libraries. 

Comlink can be used by itself, but that’s probably only interesting for framework authors and very complex apps. Clooney is a off-the-shelf solution where you don’t have to worry about the technical details of workers.

**Comment by trusktr** [comment]
What's nice about Comlink by itself, that I don't see in Clooney examples, is that with Comlink we can define a `class` inside the worker file, therefore we can use the worker file's scope outside of the `class` to store variables, etc, which is similar to writing regular ES modules. In contrast, with Clooney we loose ability to have outer scope.

It'd be nice to use files like ES modules, including their scopes, as with Comlink, but with the added conveniences of Clooney.

**Comment by surma** [comment]
Until we get modules in workers, that is not gonna be possible, sadly.

(Maybe you can kinda hack it with Babel or Rollup, but I haven’t looked into that)
